### ISSUE TITLE
Missing v4.0.0 on packagist

### ISSUE THREAD

**Issue by acelaya** [roadrunner-php/goridge#19]
I was about to update to roadrunner 2023 with roadrunner-jobs 4.0, which requires spiral/goridge 4.0. However, composer fails because there's no such version published in packagist.

![image](https://user-images.githubusercontent.com/2719332/232294028-279e92ff-c9e4-4c8e-ab71-54639ffe15af.png)

The weird thing is that there seems to be a 4.0 git tag, so maybe some automation on packagist side has failed?

**Comment by wolfy-j** [comment]
Sounds like we had a webhook issue, fixed.

**Comment by acelaya** [comment]
Thanks!
